vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

vim.opt.encoding = "UTF-8"
vim.opt.guifont = "Hack Nerd Font"
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.autoindent = true
vim.opt.tabstop = 4
-- vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.smarttab = true
vim.opt.hlsearch = true
vim.opt.mouse = a
vim.opt.expandtab = true
vim.opt.scrolloff = 5
vim.opt.colorcolumn = "101"
vim.opt.showmatch = true
vim.opt.cursorline = false
vim.opt.showmode = false
vim.opt.incsearch = true
vim.opt.laststatus = 3
